eclipse/kitalpha

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Signed-off-by: Thomas Guiu <thomas.guiu@soyatec.com>
> [releng] update tp

- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/intf/MDERichTextWidget.java
- richtext/plugins/org.polarsys.kitalpha.richtext.nebula.widget/src/org/polarsys/kitalpha/richtext/nebula/widget/MDENebulaBasedRichTextWidgetImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/MDERichtextWidgetEditorImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/MDERichtextWidgetImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/internal/ListenerInstaller.java
- Prevent loss of installed RichText listeners, after editing elements
from 2 different projects
- Add listener documentation
Bug: 560734
Change-Id: If58bab9c5d0c4d63dd426016219dc7e39b687a3a
Signed-off-by: Sandu Postaru <sandu.postaru@thalesgroup.com>
> [560734] Installed listeners on RichText are lost

- architecture description/dsl/examples/plugins/org.polarsys.kitalpha.vp.componentsample.releng/build.properties
Change-Id: I86268fffec1489128ef46f0490d2316119852f5e
> [releng] Update build properties

- composer/examples/plugins/org.polarsys.kitalpha.composer.m2t.componentsample.to.html/build.properties
- report/plugins/org.polarsys.kitalpha.report.model.edit/build.properties
- transposer/examples/plugins/org.polarsys.kitalpha.transposer.m2m.componentsample.to.uml/build.properties
Change-Id: I0f92c456daa3dea9e8b252dd1e822c27cc2b0a18
> [releng] Fix build.properties files

- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/impl/AbstractMDERichTextWidget.java
- richtext/plugins/org.polarsys.kitalpha.richtext.nebula.widget/src/org/polarsys/kitalpha/richtext/nebula/widget/MDENebulaBasedRichTextWidgetImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.ext/META-INF/MANIFEST.MF
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.ext/src/org/polarsys/kitalpha/richtext/widget/editor/ext/session/manager/CloseEditionSessionManagerListener.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/editor/MDERichTextEditor.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/helper/MDERichtextWidgetHelper.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/internal/RichtextEditorResourceSetListener.java
> V1.4.x richtext issues

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/internal/ListenerInstaller.java
Bug: 561365
Change-Id: I77ba983743289f89d91444de5665eace165620f1
Signed-off-by: Sandu Postaru <sandu.postaru@thalesgroup.com>
> [561365] Richtext can save previous description into the current element

- architecture description/core/plugins/org.polarsys.kitalpha.ad.integration.sirius/src/org/polarsys/kitalpha/ad/integration/sirius/listeners/RegisterMetadataListener.java
Bug: 563093
Signed-off-by: Laurent Redor <laurent.redor@obeo.fr>
> [563093] Avoid memory leak in ViewpointManager

- architecture description/dsl/plugins/org.polarsys.kitalpha.ad.af.dsl.servicies.project/src/org/polarsys/kitalpha/ad/af/dsl/servicies/project/ui/AFSpecProjectWizardSecondPage.java
- architecture description/dsl/plugins/org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.common/src/org/polarsys/kitalpha/ad/viewpoint/dsl/cs/text/resources/ExternalDataHelper.java
- architecture description/dsl/plugins/org.polarsys.kitalpha.ad.viewpoint.dsl.generation.build/src/org/polarsys/kitalpha/ad/viewpoint/dsl/generation/build/templates/EGFBuildHelper.java
- composer/plugins/org.polarsys.kitalpha.composer.core/src/org/polarsys/kitalpha/composer/api/CodeManagerLauncher.java
- composer/plugins/org.polarsys.kitalpha.composer.core/src/org/polarsys/kitalpha/composer/internal/standalone/CodeManagerApplication.java
- composer/plugins/org.polarsys.kitalpha.composer.ui/src/org/polarsys/kitalpha/composer/ui/launch/CodeManagerLaunchConfigurationType.java
- composer/plugins/org.polarsys.kitalpha.composer.ui/src/org/polarsys/kitalpha/composer/ui/launch/tabs/ComposerHelper.java
- composer/plugins/org.polarsys.kitalpha.composer.ui/src/org/polarsys/kitalpha/composer/ui/launch/tabs/widgets/AtomicWidget.java
- emde/plugins/org.polarsys.kitalpha.emde.xmi/src/org/polarsys/kitalpha/emde/xmi/SAXHelper.java
- squid:S2864 (findbugs:WMI_WRONG_MAP_ITERATOR)
- squid:S1068 (findbugs:UUF_UNUSED_FIELD)
- squid:S2259 (findbugs:NP_NULL_ON_SOME_PATH)
- squid:S1643 (findbugs:SBSC_USE_STRINGBUFFER_CONCATENATION)
- squid:S1172 (pmd:UnusedFormalParameter)
- pmd:AvoidDuplicateLiterals
- pmd:StringInstantiation
- findbugs:DM_STRING_CTOR
Change-Id: I1a2400a39ad6e1e8c273771ccebd0c5893df33a6
> [555863] Technical Debt.

- Jenkinsfile
Change-Id: I49ff263609f4f8250648ae06d973034cb9337662
> [releng] Udpate Jenkinsfile to deploy TP files

- releng/plugins/org.polarsys.kitalpha.releng.sdk.product/kitalpha.product
- richtext/features/org.polarsys.kitalpha.richtext.widget.feature/feature.xml
for link opening strategy
Bug: 564411
Change-Id: I678334653dc96b0d9f1d668aece298020e1d901f
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
> [564411] The Richtext feature should not include default implementation

- Jenkinsfile
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- Update TP
- Update Jenkinsfile to remove clean of entire nightly folder
Change-Id: I5f399997191b819d53a46d7b4c1a43b97c21ab1a
> [releng] Update TP for 1.4.1.IT5 and Fix Jenkinsfile

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- Update Sirius version to release 6.3.2
Change-Id: Ic9deb3ba34bfcce65cc52f44bb5c702cc3dea545
> [releng] Respin Kitalpha 1.4.1.IT5

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Revert Sirius and EGF versions
Change-Id: Ia50e8438be304c292c2918b17fb3d5385073794a
> [releng] Fix TP Update

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- Update Sirius to 6.3.3
Change-Id: Ib179787830e7a3895183af1570b744f0b650ad8c
> [releng] Update TP for 1.4.2

- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/impl/AbstractMDERichTextWidget.java
- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/intf/MDERichTextWidget.java
- richtext/plugins/org.polarsys.kitalpha.richtext.nebula.widget/src/org/polarsys/kitalpha/richtext/nebula/widget/MDENebulaBasedRichTextWidgetImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/internal/ListenerInstaller.java
The actual solution gives side-effects on Windows event (e.g. unexpected
double click event). This patch provides a way to detect if the editor
is still loading its content.
Bug: 561351
Change-Id: I4b76305f518abacabbc11779367cabddefefdbc9
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
> [561351][Richtext] Asynchronous set / save and load issues

- CONTRIBUTING.md
- NOTICE.md
Change-Id: I430dff402801cc31cce07fec01b1c5efb49d3244
> [567290] Update root repository documentation files

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- transposer/tests/plugins/junits/org.polarsys.kitalpha.transposer.junit.tests/src/org/polarsys/kitalpha/transposer/junit/tests/cases/TransformedElementOrder.java
Change-Id: I3ce0a66968b45b4026f364dab904c2aba38ddd8b
> [releng] Upgrade to generic diff/merge

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Change-Id: If4079d0b04acd10540dee06d894bdc9323c86647
> [releng] Update TP for 5.0.0-IT3

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/generated/org/polarsys/kitalpha/doc/gen/business/core/searchIndex/SearchIndex.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/task/IndexingConceptsTask.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/templates/pattern._0T5DwF4yEeGfnvXFIF-hXQ/method._0T5DxV4yEeGfnvXFIF-hXQ.pt
- Fix special characters handling in search index search field
- Make use of getEscapedForHTMLConceptName in IndexingConceptsTask
Change-Id: Icf4162ec4f6cb300beb5856b1ffb3fc4509625fd
> [569058] Special character handling in search index (report #81)

- Docgen/business/features/org.polarsys.kitalpha.doc.gen.business.core.feature/feature.xml
- Docgen/business/features/org.polarsys.kitalpha.doc.gen.business.ecore.feature/feature.xml
- Docgen/business/features/pom.xml
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core.preference/META-INF/MANIFEST.MF
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core.ui/META-INF/MANIFEST.MF
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/META-INF/MANIFEST.MF
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.ecore.genchain.edit/META-INF/MANIFEST.MF
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.ecore.genchain/META-INF/MANIFEST.MF
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.ecore/META-INF/MANIFEST.MF
- Docgen/business/plugins/pom.xml
- Docgen/business/tests/rcptt/org.polarsys.kitalpha.doc.gen.business.ecore.test.rcptt/pom.xml
- Docgen/business/tests/rcptt/org.polarsys.kitalpha.doc.gen.test.rcptt/pom.xml
Change-Id: I6775c8bf67f72d4ddb48960d7561c38befa76e5e
> [releng] Bump to 1.3.4

- Docgen/business/features/pom.xml
- Docgen/business/plugins/pom.xml
- Docgen/business/tests/rcptt/org.polarsys.kitalpha.doc.gen.business.ecore.test.rcptt/pom.xml
- Docgen/business/tests/rcptt/org.polarsys.kitalpha.doc.gen.test.rcptt/pom.xml
- product/features/org.polarsys.kitalpha.runtime.feature/feature.xml
- product/features/org.polarsys.kitalpha.sdk.feature/feature.xml
- releng/plugins/org.polarsys.kitalpha.releng.runtime.updatesite/category.xml
- releng/plugins/org.polarsys.kitalpha.releng.sdk.updatesite/category.xml
Change-Id: Ief740463b02bdebbb3076254b5cadece99d5db46
> [releng] Fix the docgen bundles parent pom references

- common/tests/org.polarsys.kitalpha.common.rcptt/test cases/Common_00001_bug.test
Change-Id: I7fd365a99b4a491173f150b454b523b9ad344262
> [rcptt] Fix common RCPTT test

- architecture description/core/plugins/org.polarsys.kitalpha.ad.integration.sirius/src/org/polarsys/kitalpha/ad/integration/sirius/listeners/ViewpointActivationStateListener.java
Signed-off-by: Guillaume Coutable <guillaume.coutable@obeo.fr>
> eclipse#645 Support viewpoint not registered in ViewpointRegistry

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/messages/Messages.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/messages/messages.properties
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/util/EscapeChars.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/util/LabelProviderHelper.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/visitor/DocgenCommonSubClassEmfModelVisitor.java
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Prevent documentation generation errors by handling null references in
input model.
Add error management and default behavior.
Change-Id: Ie4566aebeba2762015652e8f212240d7fd266868
> #650 Null reference handling

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Change-Id: I06076449004d3fc4ddb8aad823c0b425f06cb197
> [releng] Update TP for 5.1.0-IT1

- transposer/tests/plugins/rcptt/org.polarsys.kitalpha.transposer.rcptt.tests/pom.xml
Change-Id: I02ff53e5fe640f59f25ec7c98af24d44d928764e
> [releng] Fix missing pom version update

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Modification linked to Eclipse ticket:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572437
Change-Id: I733fe7503742eaaa78a22c18b516a96dff2bff6e
> [releng] Update TP to include Amalgam 1.12.1

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/sirius/util/diagram/CoordinatesCalculator.java
Finally clause added to ensure FIS closing but prevously present close
still present.
Change-Id: I2c4c0d8a24cfc0faa62e3d3d5182c66093f70dca
> #239 Fix regression in modification

- README.md
Change-Id: I7c6153f74a1bac4c7596d4fbcecf713adb63baab
> [releng] Add README file

- releng/plugins/org.polarsys.kitalpha.releng.parent/pom.xml
Change-Id: I5e5d1a9af9f56b328859bb84d8ca70ec9120c271
> #681 Update Jarsigner plugin

- releng/plugins/org.polarsys.kitalpha.releng.aggregator.tests/pom.xml
- releng/plugins/org.polarsys.kitalpha.releng.parent/pom.xml
Modify RCPTT version to latest nightly
Change-Id: I7e04f1688b8f2e48d7ebe80fc1d141088dcb2085
> [RCPTT] Reactivate RCPTT tests

- architecture description/metadata/tests/org.polarsys.kitalpha.ad.metadata.tests/tests/org/polarsys/kitalpha/ad/metadata/tests/AdMetaDataTestSuite.java
- architecture description/metadata/tests/org.polarsys.kitalpha.ad.metadata.tests/tests/org/polarsys/kitalpha/ad/metadata/tests/UpdateReferencedViewpointsTests.java
- detachment/plugins/org.polarsys.kitalpha.model.common.scrutiny.contrib.viewpoints/src/org/polarsys/kitalpha/model/common/scrutiny/contrib/viewpoints/scrutinizes/UsedAFViewpoints.java
- releng/features/org.polarsys.kitalpha.releng.runtime.core.feature/feature.xml
- releng/plugins/org.polarsys.kitalpha.releng.runtime.core.updatesite/category.xml
- releng/plugins/org.polarsys.kitalpha.releng.runtime.updatesite/category.xml
Fix plugins update site diffusion for open sources features (#686 & #688).
Fix bug (#691)
> #686 #688 + #691 master-6.0

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalphaWithRuntimeCore.target
* Sirius 6.6.0-S20211126-081944/2020-06
Change-Id: I04b84cee73360f425cf738cedfd1b36770e3cfa8
> [releng] Update Target platform for 5.2.0-IT3

- releng/plugins/org.polarsys.kitalpha.releng.sdk.product/pom.xml
Remove tempered jar content for deprecated richtext-ie/edge compatibility issue fix
> Richtext jar fix

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Change-Id: Ie857c2d9781d882e39af2d8df651f51670483491
> [releng] Integrate Sirius 7.0.1-S20220314-093652

- releng/plugins/org.polarsys.kitalpha.releng.parent/pom.xml
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- Amalgam 1.13.0-S20220524
- Diffmerge 0.14.0-S20220524
- Sirius 7.0.1-S20220519-115310
Change-Id: Ie3127d45c7dc6856718f2b6e007cbb1bd6a967f7
> [releng] Integrate Sirius 7.0.1-S20220519, Amalgam and Diffmerge

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- Amalgam 1.13.0-S20220629
- Diffmerge 0.14.0-S20220629
- Sirius 7.0.2rc2
> [releng] Integrate Sirius 7.0.2rc2, Amalgam and Diffmerge

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
> [releng] Update Sirius and Diffmerge

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.target
- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Change-Id: If00ed715bc7a86bf9159075542463b29fa050c19
> [releng] Update Diffmerge

- sirius/plugins/org.polarsys.kitalpha.sirius.rotativeimage/src/org/polarsys/kitalpha/sirius/rotativeimage/editpart/RotativeImageEditPart.java
Bug: https://github.com/eclipse/kitalpha/issues/744
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>
> #744 Limit the number of times the rotative port are drawn

- richtext/plugins/org.polarsys.kitalpha.richtext.widget.ext/META-INF/MANIFEST.MF
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/dialogs/IEncodedURLHandler.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/dialogs/MDELinkDialog.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/handlers/AddLinkHandler.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/manager/LinkManagerImpl.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/messages/Messages.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/messages/messages.properties
label field is initialized with old label
fixed small issue where OK button could be pressed even though mandatory info are empty
Change-Id: I7ec75f37ad7ce5d7ae08452ba88c1a0e2a76db4e
> #750 Added new Dialog to select Model element / Diagram Element

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
- richtext/plugins/org.polarsys.kitalpha.richtext.widget.ext/META-INF/MANIFEST.MF
Wrongly add on https://github.com/eclipse/kitalpha/pull/751/files#diff-28880344adbebf6e3c8f3a6285d20cef817710f8b9efcf40f0b20edfcdf09bf3R28
> #750 Fix non existing Exported Package

- richtext/plugins/org.polarsys.kitalpha.richtext.widget.tools/src/org/polarsys/kitalpha/richtext/widget/tools/utils/MDERichTextToolsHelper.java
Also added a function to decode these whitespaces
Change-Id: Id02ad44c0fa5bff88eb4f7b1d88325520109f2d2
> #756 Whitespace are encoded in &#160 instead of &nbsp;

- richtext/plugins/org.polarsys.kitalpha.richtext.nebula.widget/src/org/polarsys/kitalpha/richtext/nebula/widget/MDERichTextConstants.java
- richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/factory/MDERichTextFactory.java
Removed Lorem ipsum text in Image Properties preview
Change-Id: Ic2ccf8fb29d0268475df80ae31fb49d868f7ea0d
> #762 Removed Dummy text in Richtext image preview

- releng/plugins/org.polarsys.kitalpha.releng.sdk.product/kitalpha.product
IE support ending soon, edge shall be used as default browser on windows
Change-Id: I24700612e084769fb30d7b7a14bc24e20449acdc
> #766 Product now uses Edge as default browser on windows

- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/impl/AbstractMDERichTextWidget.java
Make sure that getSaveStrategy().save is not called during the call of org.polarsys.kitalpha.richtext.common.impl.AbstractMDERichTextWidget.loadContent()
> #770 Avoid infinite loop when pasting an image in the richText editor

- releng/plugins/org.polarsys.kitalpha.releng.targets/kitalpha.targetplatform
Update to 7.2.0
Change-Id: If9cd0fddcc995f942144ab219b1b446a26147650
> [releng] Update Sirius in targetplatform

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/generated/org/polarsys/kitalpha/doc/gen/business/core/doccontent/ElementDocContent.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/generated/org/polarsys/kitalpha/doc/gen/business/core/doccontent/sidebar/ElementSideBarHeader.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/task/IndexingConceptsTask.java
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/templates/pattern._lERcoN3tEd-Qav1YnqlO9A/method._lERcpd3tEd-Qav1YnqlO9A.pt
- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/templates/pattern._zflfEPepEd-vRuaiXg4Fzg/method._zflfFfepEd-vRuaiXg4Fzg.pt
UTF-8 instead of ISO-8859-1
Change-Id: I3a2617f5691cf3944ae68b27c388d3357f37fce3
> #785 Docgen encoding set to UTF-8

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/scope/GenerationGlobalScope.java
Change-Id: Id1d5a331af3074a71ebc5bccf341df91a97ee2ff
> #781 Memory:/ URI wasn't used

- Docgen/business/plugins/org.polarsys.kitalpha.doc.gen.business.core/src/org/polarsys/kitalpha/doc/gen/business/core/util/DocGenHtmlUtil.java
Change-Id: I0bdade17ed8d6645c269bd74b17a99f3ea987007
> #785 Forces HTML serialization to UTF-8

- richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/impl/AbstractMDERichTextWidget.java
Change-Id: I81fef54aa838cce776b7669919c42de58c838585
> #788 Rich text widget now only saves content if the elements is owned by a session
